--CREATE TABLE `pessoas` (
--  `id` int NOT NULL AUTO_INCREMENT,
--  `nome` varchar(25) NOT NULL,
--  `sobrenome` varchar(50) NOT NULL,
--  `endereco` varchar(100) NOT NULL,
--  `sexo` varchar(10) NOT NULL,
--  PRIMARY KEY (`id`)
--) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

--INSERT PARA TESTAR OS GETS
--insert into api_rest_with_dotnet.pessoas (
--	id, nome, sobrenome, endereco, sexo
--    )
--    VALUES (1, "Iago", "Martuci", "Rua Teste, 100", "Masculino");